services:
  - type: web
    name: FantasyStaffApp
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

databases:
  - name: my-database
    type: postgres

